name: LeetCode Sync Bot

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF: ${{ secrets.LEETCODE_CSRF }}
        run: python bot.py

      - name: Commit & Push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if [ -f commit_msg.txt ]; then
            MSG=$(cat commit_msg.txt)
          else
            MSG="Auto update LeetCode solutions"
          fi

          git diff --cached --quiet || git commit -m "$MSG"

          git pull --rebase
          git push