name: LeetCode Sync Bot

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

concurrency:
  group: leetcode-sync
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------
      # Checkout repo
      # ----------------------------
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ----------------------------
      # Setup Python
      # ----------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ----------------------------
      # Install dependencies
      # ----------------------------
      - name: Install dependencies
        run: pip install -r requirements.txt

      # ----------------------------
      # Run bot
      # ----------------------------
      - name: Run bot
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF: ${{ secrets.LEETCODE_CSRF }}
        run: python bot.py

      # ----------------------------
      # Commit & Push
      # ----------------------------
      - name: Commit & Push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if [ -f commit_msg.txt ]; then
            MSG=$(cat commit_msg.txt)
          else
            MSG="Auto update LeetCode solutions"
          fi

          if ! git diff --cached --quiet; then
            git commit -m "$MSG"

            # Sync before push
            git pull --rebase origin main

            git push origin main
          else
            echo "No changes to commit"
          fi